const peopleDB = [
    {
      "nombre": "Ana María Mosquera",
      "genero": "Mujer",
      "edad": 20,
      "ciudad": "Popayan",
      "salir": true,
      "dificultad": 5,
      "dias": 2,
      "gimnasio": 3,
      "nadar": 10,
      "pesca": 2,
      "escalada": 1,
      "mirador": 10
    },
    {
      "nombre": "Gabriela Villa Soto",
      "genero": "Mujer",
      "edad": 58,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 4,
      "dias": 7,
      "gimnasio": 2,
      "nadar": 7,
      "pesca": 5,
      "escalada": 1,
      "mirador": 8
    },
    {
      "nombre": "María Teresa Gutierrez Villa",
      "genero": "Mujer",
      "edad": 43,
      "ciudad": "Puerto Tejada",
      "salir": true,
      "dificultad": 4,
      "dias": 3,
      "gimnasio": 5,
      "nadar": 10,
      "pesca": 5,
      "escalada": 9,
      "mirador": 9
    },
    {
      "nombre": "Maria Camila Mora Rivas",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Bogota",
      "salir": true,
      "dificultad": 8,
      "dias": 10,
      "gimnasio": 1,
      "nadar": 3,
      "pesca": 2,
      "escalada": 6,
      "mirador": 4
    },
    {
      "nombre": "Camilo pascuas",
      "genero": "Hombre",
      "edad": 24,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 6,
      "dias": 6,
      "gimnasio": 1,
      "nadar": 2,
      "pesca": 3,
      "escalada": 4,
      "mirador": 5
    },
    {
      "nombre": "Maria Jose Barney",
      "genero": "Mujer",
      "edad": 19,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 7,
      "dias": 5,
      "gimnasio": 6,
      "nadar": 10,
      "pesca": 4,
      "escalada": 7,
      "mirador": 9
    },
    {
      "nombre": "Manuel Bustamante",
      "genero": "Hombre",
      "edad": 21,
      "ciudad": "Barranquilla",
      "salir": true,
      "dificultad": 7,
      "dias": 10,
      "gimnasio": 9,
      "nadar": 9,
      "pesca": 9,
      "escalada": 9,
      "mirador": 9
    },
    {
      "nombre": "Abimael villalba",
      "genero": "Hombre",
      "edad": 20,
      "ciudad": "Fundacion",
      "salir": true,
      "dificultad": 4,
      "dias": 7,
      "gimnasio": 10,
      "nadar": 9,
      "pesca": 8,
      "escalada": 7,
      "mirador": 6
    },
    {
      "nombre": "Luis montt",
      "genero": "Hombre",
      "edad": 20,
      "ciudad": "Cartagena",
      "salir": true,
      "dificultad": 4,
      "dias": 1,
      "gimnasio": 9,
      "nadar": 8,
      "pesca": 6,
      "escalada": 7,
      "mirador": 10
    },
    {
      "nombre": "Daniela Estefanía López Ojeda",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Pasto",
      "salir": true,
      "dificultad": 6,
      "dias": 7,
      "gimnasio": 8,
      "nadar": 10,
      "pesca": 7,
      "escalada": 7,
      "mirador": 10
    },
    {
      "nombre": "Kendrick Lamar",
      "genero": "Hombre",
      "edad": 19,
      "ciudad": "Barranquilla",
      "salir": true,
      "dificultad": 10,
      "dias": 10,
      "gimnasio": 9,
      "nadar": 8,
      "pesca": 7,
      "escalada": 6,
      "mirador": 5
    },
    {
      "nombre": "Alejandro Castro",
      "genero": "Hombre",
      "edad": 22,
      "ciudad": "Palmira",
      "salir": true,
      "dificultad": 6,
      "dias": 6,
      "gimnasio": 6,
      "nadar": 8,
      "pesca": 9,
      "escalada": 7,
      "mirador": 10
    },
    {
      "nombre": "Laura Barrera Valdés",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 10,
      "dias": 10,
      "gimnasio": 9,
      "nadar": 9,
      "pesca": 9,
      "escalada": 9,
      "mirador": 9
    },
    {
      "nombre": "Laura Victoria Aguilar Rivas",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 7,
      "dias": 8,
      "gimnasio": 9,
      "nadar": 10,
      "pesca": 1,
      "escalada": 6,
      "mirador": 8
    },
    {
      "nombre": "Johan Gutierrez",
      "genero": "Hombre",
      "edad": 22,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 6,
      "dias": 4,
      "gimnasio": 4,
      "nadar": 7,
      "pesca": 6,
      "escalada": 5,
      "mirador": 7
    },
    {
      "nombre": "Juan Felipe Blanco",
      "genero": "Hombre",
      "edad": 18,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 6,
      "dias": 2,
      "gimnasio": 2,
      "nadar": 3,
      "pesca": 1,
      "escalada": 4,
      "mirador": 5
    },
    {
      "nombre": "Miguel Enrique Barrera Tasama",
      "genero": "Hombre",
      "edad": 57,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 5,
      "dias": 5,
      "gimnasio": 10,
      "nadar": 9,
      "pesca": 9,
      "escalada": 7,
      "mirador": 8
    },
    {
      "nombre": "José Alejandro Londoño García",
      "genero": "Hombre",
      "edad": 21,
      "ciudad": "Palmira",
      "salir": false,
      "dificultad": 4,
      "dias": 1,
      "gimnasio": 9,
      "nadar": 4,
      "pesca": 10,
      "escalada": 5,
      "mirador": 8
    },
    {
      "nombre": "Laura sofia castañeda velasquez",
      "genero": "Mujer",
      "edad": 17,
      "ciudad": "Buga",
      "salir": true,
      "dificultad": 6,
      "dias": 4,
      "gimnasio": 7,
      "nadar": 10,
      "pesca": 8,
      "escalada": 8,
      "mirador": 10
    },
    {
      "nombre": "Paola Andrea Velásquez Castro",
      "genero": "Mujer",
      "edad": 43,
      "ciudad": "Buga",
      "salir": true,
      "dificultad": 5,
      "dias": 6,
      "gimnasio": 10,
      "nadar": 9,
      "pesca": 8,
      "escalada": 2,
      "mirador": 7
    },
    {
      "nombre": "Juan David Lopez",
      "genero": "Hombre",
      "edad": 20,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 6,
      "dias": 8,
      "gimnasio": 2,
      "nadar": 5,
      "pesca": 1,
      "escalada": 5,
      "mirador": 7
    },
    {
      "nombre": "Leidy yuliana quevedo jaramillo",
      "genero": "Mujer",
      "edad": 25,
      "ciudad": "Torrevieja",
      "salir": true,
      "dificultad": 6,
      "dias": 6,
      "gimnasio": 2,
      "nadar": 3,
      "pesca": 4,
      "escalada": 1,
      "mirador": 5
    },
    {
      "nombre": "Juan Pablo Roldan Caicedo",
      "genero": "Prefiero no decirlo",
      "edad": 22,
      "ciudad": "Tulua",
      "salir": true,
      "dificultad": 8,
      "dias": 7,
      "gimnasio": 1,
      "nadar": 2,
      "pesca": 1,
      "escalada": 1,
      "mirador": 10
    },
    {
      "nombre": "Daniel Alejandro Ruiz López",
      "genero": "Hombre",
      "edad": 23,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 8,
      "dias": 7,
      "gimnasio": 5,
      "nadar": 9,
      "pesca": 7,
      "escalada": 8,
      "mirador": 10
    },
    {
      "nombre": "Daniel Camilo Villalobos Arboleda",
      "genero": "Hombre",
      "edad": 22,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 7,
      "dias": 1,
      "gimnasio": 1,
      "nadar": 10,
      "pesca": 2,
      "escalada": 3,
      "mirador": 9
    },
    {
      "nombre": "Sara Lucia Quevedo Jaramillo",
      "genero": "Mujer",
      "edad": 18,
      "ciudad": "Tulua",
      "salir": true,
      "dificultad": 8,
      "dias": 9,
      "gimnasio": 3,
      "nadar": 9,
      "pesca": 4,
      "escalada": 8,
      "mirador": 10
    },
    {
      "nombre": "Eliana Gil Palacios",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Tulua",
      "salir": true,
      "dificultad": 9,
      "dias": 9,
      "gimnasio": 3,
      "nadar": 4,
      "pesca": 2,
      "escalada": 3,
      "mirador": 4
    },
    {
      "nombre": "Jorge Alejandro Zuñiga Moraga",
      "genero": "Hombre",
      "edad": 21,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 9,
      "dias": 10,
      "gimnasio": 10,
      "nadar": 10,
      "pesca": 2,
      "escalada": 8,
      "mirador": 10
    },
    {
      "nombre": "Karen Andrade",
      "genero": "Mujer",
      "edad": 20,
      "ciudad": "Pereira",
      "salir": true,
      "dificultad": 8,
      "dias": 9,
      "gimnasio": 8,
      "nadar": 2,
      "pesca": 1,
      "escalada": 9,
      "mirador": 10
    },
    {
      "nombre": "Valeria Ramirez",
      "genero": "Mujer",
      "edad": 23,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 5,
      "dias": 6,
      "gimnasio": 3,
      "nadar": 8,
      "pesca": 2,
      "escalada": 4,
      "mirador": 10
    },
    {
      "nombre": "Inés María Linares Aguirre",
      "genero": "Mujer",
      "edad": 23,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 9,
      "dias": 10,
      "gimnasio": 8,
      "nadar": 6,
      "pesca": 1,
      "escalada": 7,
      "mirador": 10
    },
    {
      "nombre": "Laura Marcela Peña Molina",
      "genero": "Mujer",
      "edad": 23,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 10,
      "dias": 5,
      "gimnasio": 1,
      "nadar": 2,
      "pesca": 3,
      "escalada": 4,
      "mirador": 5
    },
    {
      "nombre": "Daniel Figueroa",
      "genero": "Hombre",
      "edad": 20,
      "ciudad": "Cali",
      "salir": false,
      "dificultad": 7,
      "dias": 6,
      "gimnasio": 1,
      "nadar": 8,
      "pesca": 2,
      "escalada": 3,
      "mirador": 1
    },
    {
      "nombre": "Juanita hoyos",
      "genero": "Mujer",
      "edad": 21,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 10,
      "dias": 10,
      "gimnasio": 1,
      "nadar": 6,
      "pesca": 7,
      "escalada": 8,
      "mirador": 9
    },
    {
      "nombre": "Karen Marcela Poveda",
      "genero": "Mujer",
      "edad": 24,
      "ciudad": "Palmira",
      "salir": true,
      "dificultad": 7,
      "dias": 7,
      "gimnasio": 3,
      "nadar": 8,
      "pesca": 3,
      "escalada": 3,
      "mirador": 8
    },
    {
      "nombre": "Karen Castañeda",
      "genero": "Mujer",
      "edad": 20,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 7,
      "dias": 7,
      "gimnasio": 7,
      "nadar": 9,
      "pesca": 2,
      "escalada": 2,
      "mirador": 8
    },
    {
      "nombre": "Ana Lisa Parra",
      "genero": "Mujer",
      "edad": 45,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 5,
      "dias": 5,
      "gimnasio": 3,
      "nadar": 5,
      "pesca": 7,
      "escalada": 2,
      "mirador": 9
    },
    {
      "nombre": "Luis Carlos Ramirez",
      "genero": "Hombre",
      "edad": 20,
      "ciudad": "Cali",
      "salir": true,
      "dificultad": 3,
      "dias": 4,
      "gimnasio": 9,
      "nadar": 10,
      "pesca": 3,
      "escalada": 6,
      "mirador": 10
    },
    {
      "nombre": "Jennifer Rodríguez Velázquez",
      "genero": "Mujer",
      "edad": 25,
      "ciudad": "Buga",
      "salir": true,
      "dificultad": 5,
      "dias": 1,
      "gimnasio": 1,
      "nadar": 8,
      "pesca": 10,
      "escalada": 1,
      "mirador": 8
    }
];