const routesDB = [
    {
        nombre: "Sendero Pico de Loro",
        dificultad: 7,
        ubicacion: "Cali",
        imagen: "picoLoro.jpg",
        actividades: ["Avistamiento de aves", "Mirador"],
        duración: 4,
        informacion: "Partiendo a 1718m sobre el nivel del mar, te espera una caminata de aproximadamente 4 horas por los farallones de Cali que se eleva hasta los 2860m sobre el nivel del mar. Realizar esta caminata requiere reservación.",
        enlace: "http://picoloro.co/me-interesa/?ID=4018",
    },
    {
        nombre: "Pico de Águila",
        dificultad: 4,
        ubicacion: "Cali",
        imagen: "picoAguila.jpg",
        actividades: ["Mirador"],
        duración: 4,
        informacion: "Es una salida especialmente preparada para personas que quieren iniciarse en el mundo de las caminatas ecológicas. Durante el camino se tiene excelente vista de La Vorágine, Chorro de Plata y los farallones de Cali, y al finalizar la caminata, se llega a un mirador con una vista espectacular de toda la ciudad de Cali.",
        enlace: "http://picoloro.co/me-interesa/?ID=4301",
    },
    {
        nombre: "Peñas Blancas",
        dificultad: 8,
        ubicacion: "Cali",
        imagen: "peñasBlancas.jpg",
        actividades: ["Río", "Escalada"],
        duración: 4,
        informacion: "Esta caminata es recomendada para personas con buena condición física y experiencia en actividades al aire libre. Caminando a través de un bosque de pinos y eucalipto, por un sendero empinado en el que tendrás que, a veces, tendrás que utilizar también las manos para avanzar, hasta llegar a 2900m sobre el nivel del mar, desde donde se puede observar el Alto del Buey. Al regresar, se puede disfrutar de las aguas del Río Pichindé.",
        enlace: "http://picoloro.co/me-interesa/?ID=4677",
    },
    {
        nombre: "Laguna del Otún",
        dificultad: 9,
        ubicacion: "Pereira",
        imagen: "lagunaOtun.jpg",
        actividades: ["Mirador", "Avistamiento de aves"],
        duración: 72,
        informacion: "Esta caminata de 3 días es una travesía a través del Parque Natural los Nevados. Partiendo desde Pereira, el recorrido sigue el río Otún hasta llegar a la gran masa de agua que es La Laguna del Otún, para finalmente, atravesar unos enormes pastizales que conducen a las estribaciones de Santa Rosa de Cabal.",
        enlace: "http://picoloro.co/me-interesa/?ID=3843",
    },
    {
        nombre: "Minas",
        dificultad: 2,
        ubicacion: "Jamundí",
        imagen: "minas.jpg",
        actividades: ["Escalada"],
        duración: 1,
        informacion: "El principal atractivo de esta caminata es su zona de escalada en roca, con rutas de escalada de todos los niveles, haciendolo un destino ideal para aquellos que quieran experimentar la escalada por primera vez o quienes ya tienen experiencia. Para llegar a Minas es necesario contar con un guía, así como alquilar el equipo de seguridad para escalar.",
        enlace: "https://www.facebook.com/Arawata-Club-de-Escalada-265104433519197",
    },
    {
        nombre: "Dapa",
        dificultad: 3,
        ubicacion: "Cali",
        imagen: "dapa.jpg",
        actividades: ["Escalada", "Mirador"],
        duración: 1,
        informacion: "Considerada por muchos escaladores caleños como el mejor lugar para escalar en roca de la ciudad y sus alrededores, esta caminata ofrece una experiencia maravillosa para cualquiera que quiera experimentar la escalada en roca, desde novatos hasta expertos. Cuenta también con una maravillosa vista de la ciudad y una zona disponible para acampar.",
        enlace: "https://www.facebook.com/Arawata-Club-de-Escalada-265104433519197",
    },
    {
        nombre: "Cerro de las Tres Cruces",
        dificultad: 3,
        ubicacion: "Cali",
        imagen: "tresCruces.jpg",
        actividades: ["Gimansio", "Mirador"],
        duración: 2,
        informacion: "Una de las caminatas más famosas de Cali, en donde es tradición para algunos realizarla cada domingo. Con una dificultad relativamente baja y de fácil acceso, esta es una ruta muy recomendada para cualquiera que quiera hacer un poco de ejercicio y tener una excelente vista de la ciudad.",
        enlace: "http://picoloro.co/rutas-en-el-cerro-de-las-tres-cruces-en-cali/",
    },
    {
        nombre: "Charco escondido",
        dificultad: 2,
        ubicacion: "Jamundí",
        imagen: "charcoEscondido.jpg",
        actividades: ["Río"],
        duración: 1,
        informacion: "Esta caminata es una de las más populares para caleños y jamundeños, es una camina sin mucha pendiente hasta llegar al charco, donde podrás bañar en la refrescante y cristalina agua que lo hace tan famoso. El charco es propiedad privada y la entrada cuesta $2.000.",
        enlace: "https://blog.redbus.co/naturaleza/charco-escondido-conoce-este-tesoro-natural-del-valle-del-cauca/",
    },
    {
        nombre: "Parque de la salud",
        dificultad: 1,
        ubicacion: "Cali",
        imagen: "pance.jpg",
        actividades: ["Río", "Gimnasio"],
        duración: 1,
        informacion: "Este famoso parque contiene un sendero que da la vuelta a todo el lugar, el recorrido es sencillo y sin pendiente. Además, puedes utilizar los lugares de ejercicio que dispone el parque, así como las canchas para jugar futbol, baloncesto y otros deportes. Finalmente, uno de los mayores atractivos del parque, es el Río Pance, donde podrás nadar en sus refrescantes aguas.",
        enlace: "https://www.tripadvisor.co/Attraction_Review-g297475-d8855646-Reviews-Parque_de_La_Salud-Cali_Valle_del_Cauca_Department.html",
    },
    {
        nombre: "Nevado del Tolima",
        dificultad: 10,
        ubicacion: "Cali",
        imagen: "pance.jpg",
        actividades: ["Mirador"],
        duración: 96,
        informacion: "Esta caminata es perfecta si lo que buscas es estar en contacto puro con la naturaleza. Partiendo desde Salento, a 1895 metros de altura sobre el nivel del mar, la ruta sigue durante 2 días hasta llegar al majestuoso Nevado del Tolima, a 5210 metros sobre el nivel del mar. Para esta caminata se recomienda contar con buen estado físico y experiencia previa en montañismo.",
        enlace: "http://picoloro.co/salidas/nevado-del-tolima-4-dias/",
    },
]